name: Pull Request For Develop
on: 
  pull_request:
    types: [opened, reopened]
    branches: 
      - "develop"
jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
          architecture: 'x64'
      - name: Run unit tests
        run: |
          pip install pytest
          pytest
      - name: Run linting
        run: |
          pip install flake8
          flake8
