name: PR Actions For Master

on: 
  pull_request:
    types: [opened, reopened]    
    branches:
      - "master"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
            
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        export PYTHONPATH=src
        pytest --cov=./ --cov-report=xml
  
    - name: Wemake Python Stylguide
      uses: wemake-services/wemake-python-styleguide@0.15.2
      continue-on-error: true
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        verbose: true
